INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Altre', 'MISC', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammatica - Aggettivi', 'CAT1', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammatica - Articoli', 'CAT2', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammatica - Elisioni e troncamenti', 'CAT3', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammatica - Frase', 'CAT4', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammatica - Preposizioni', 'CAT5', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammatica - Punteggiatura', 'CAT6', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammatica - Verbi', 'CAT7', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Possibile errore di battitura', 'TYPOS', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Punteggiatura', 'PUNCTUATION', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Stile - Espressioni', 'CAT8', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Stile - Frase', 'CAT9', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Stile - Leggibilità', 'CAT10', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Stile - Numeri', 'CAT11', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Tipografia', 'TYPOGRAPHY', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Ulteriori errori comuni - ortografia', 'CAT13', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Ulteriori errori comuni - voci del verbo ''avere''', 'CAT12', 'it');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Uso delle maiuscole', 'CASING', 'it');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Capitalization', 'CASING', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Collocations', 'COLLOCATIONS', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Commonly Confused Words', 'CONFUSED_WORDS', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammar', 'GRAMMAR', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Miscellaneous', 'MISC', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Misused terms in EU publications (Gardner)', 'MISUSED_TERMS_EU_PUBLICATIONS', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Nonstandard Phrases', 'NONSTANDARD_PHRASES', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Plain English', 'PLAIN_ENGLISH', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Possible Typo', 'TYPOS', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Punctuation', 'PUNCTUATION', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Punctuation Errors', 'PUNCTUATION', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Redundant Phrases', 'REDUNDANCY', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Semantic', 'SEMANTICS', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Style', 'STYLE', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Typography', 'TYPOGRAPHY', 'en');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Wikipedia', 'WIKIPEDIA', 'en');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Anglicismes (calques, emprunts directs, etc.)', 'TYPOGRAPHY', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Archaïsmes (tours vieillis, anciens et vieux)', 'CAT_ARCHAISMES', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Confusion d’homonymes et paronymes', 'CAT_HOMONYMES_PARONYMES', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Faute de frappe possible', 'TYPOS', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammaire', 'CAT_GRAMMAIRE', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Majuscules', 'CASING', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Marques de commerce', 'CAT_MARQUES_DE_COMMERCE', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Pléonasmes', 'CAT_PLEONASMES', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Ponctuation', 'PUNCTUATION', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Règles de base', 'MISC', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Régionalismes', 'CAT_REGIONALISMES', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Tours critiqués divers (barbarismes, impropriétés, solécismes, etc.)', 'CAT_TOURS_CRITIQUES', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Typographie', 'TYPOGRAPHY', 'fr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Élision', 'CAT_ELISION', 'fr');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Concordancia', 'CAT2', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Concordancia predicativa', 'CAT3', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Diversas', 'MISC', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Estilo', 'CAT4', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Gramática', 'GRAMMAR', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Mayúsculas y minúsculas', 'CASING', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Mecanografía', 'TYPOGRAPHY', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Ortografía (concepto)', 'CAT1', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Ortografía (tipográficos)', 'TYPOS', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Posible error tipográfico', 'TYPOS', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Puntuación', 'PUNCTUATION', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Reglas específicas para Wikipedia', 'WIKIPEDIA', 'es');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Cambios en las normas lingüísticas', 'CAMBIOS_NORMA', 'es');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Aandachtspunten in de betekenis en consistentie.', 'SEMANTICS', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Aandachtspunten rond o.a. punten en aanhalingstekens.', 'TYPOGRAPHY', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Aaneen of los', 'COMPOUNDING', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Afkortingen', 'AFKORTINGEN', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Beledigend', 'BELEDIGEND', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Bungelend', 'BUNGELEND', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Congruentie', 'CONGRUENTIE', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Constructiefout', 'CONSTRUCTIEFOUT', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Diverse regels', 'OVERIG', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Diversen', 'MISC', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Eigennamen beroemdheden etc.', 'EIGENNAMEN', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Gemakkelijk te verwarren woorden', 'CONFUSED_WORDS', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Geografie', 'GEOGRAFIE', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Getallen', 'GETALLEN', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Herhaling van woorden of woordgroepen.', 'REPETITIONS', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Hoofdlettergebruik', 'CASING', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Hoofdletters', 'CASING', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Informeel', 'COLLOQUIALISMS', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Interpunctie', 'PUNCTUATION', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Leenwoorden met een gangbaar alternatief', 'LEENWOORDEN', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Leesbaarheid', 'LEESBAARHEID', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Mogelijke typefouten', 'TYPOS', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Notaties', 'NOTATIES', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Ouderwets', 'OUDERWETS', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Spellingcontrole', 'TYPOS', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Stijlkwesties', 'STYLE', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Streektaal', 'STREEKTAAL', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Typografie', 'TYPOGRAPHY', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Uit: Aarsrivalen, scheldkarbonades en terminale baden', 'AARSRIVALEN', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Uit: Hoe bereidt je een paard? : clichés', 'CLICHES', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Vaste uitdrukkingen', 'VASTE_UITDRUKKINGEN', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Vergissingen', 'VERGISSINGEN', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Verschil België en Nederland', 'BE_NL', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Voluit schrijven', 'VOLUIT_SCHRIJVEN', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Vormfouten', 'VORMFOUTEN', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Woordgroepen', 'WOORDGROEPEN', 'nl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Woordverwarring', 'CONFUSED_WORDS', 'nl');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Briefe und E-Mails', 'CORRESPONDENCE', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Empfohlene Rechtschreibung laut Duden', 'EMPFOHLENE_RECHTSCHREIBUNG', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Geschlechtergerechte Sprache', 'GENDER_NEUTRALITY', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Getrennt- und Zusammenschreibung', 'COMPOUNDING', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammatik', 'GRAMMAR', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Groß-/Kleinschreibung', 'CASING', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Hilfestellung für Kommasetzung', 'HILFESTELLUNG_KOMMASETZUNG', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Leicht zu verwechselnde Wörter', 'CONFUSED_WORDS', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Mögliche Tippfehler', 'TYPOS', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Prominente/geographische Eigennamen', 'PROPER_NOUNS', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Redewendungen', 'IDIOMS', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Redundanz', 'REDUNDANCY', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Semantische Unstimmigkeiten', 'SEMANTICS', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Sonstiges', 'MISC', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Stil', 'STYLE', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Typographie', 'TYPOGRAPHY', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Umgangssprache', 'COLLOQUIALISMS', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Wikipedia', 'WIKIPEDIA', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Zeichensetzung', 'PUNCTUATION', 'de');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Zusammen-/Getrenntschreibung', 'COMPOUNDING', 'de');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Calinadas', 'EGGCORNS', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Capitalização', 'CASING', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Confusão de Palavras', 'CONFUSED_WORDS', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Contrações', 'CONTRACTIONS', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Desenvolvimento', 'DEVELOPMENT', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Erros Ortográficos', 'MISSPELLING', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Erros de Tradução', 'TRANSLATION_ERRORS', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Estilo', 'STYLE', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Frases-feitas e expressões idiomáticas', 'CLICHES', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Gramática Geral', 'GRAMMAR', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Linguagem Formal', 'FORMAL_SPEECH', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Palavras Compostas', 'COMPOUNDING', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Pontuação', 'PUNCTUATION', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Redundância', 'REDUNDANCY', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Regras de Marcas e Termos Registados', 'REGISTERED_BRANDS', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Repetições', 'REPETITIONS', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Sem Categoria Definida', 'MISC', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Semântica', 'SEMANTICS', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Sintaxe', 'SYNTAX', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Tipografia', 'TYPOGRAPHY', 'pt');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Wikipédia', 'WIKIPEDIA', 'pt');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Грамматика', 'GRAMMAR', 'ru');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Дополнительные правила', 'EXTEND', 'ru');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Заглавные буквы', 'CASING', 'ru');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Логические ошибки', 'LOGIC', 'ru');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Общие правила', 'MISC', 'ru');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Проверка орфографии', 'TYPOS', 'ru');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Пунктуация', 'PUNCTUATION', 'ru');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Стиль', 'STYLE', 'ru');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Типографика', 'TYPOGRAPHY', 'ru');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Agreement', 'AGREEMENT', 'el');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Homonymy', 'HOMONYMY', 'el');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Orthography', 'ORTHOGRAPHY', 'el');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Redundant Phrases', 'REDUNDANCY', 'el');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Syntax', 'SYNTAX', 'el');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Διάφορα', 'MISC', 'el');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Πιθανό λάθος', 'TYPOS', 'el');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Στίξη', 'PUNCTUATION', 'el');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Τυπογραφικά', 'TYPOGRAPHY', 'el');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Υφολογικά λάθη', 'STYLE', 'el');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Χρήση κεφαλαίων', 'CASING', 'el');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Punctuation', 'PUNCTUATION', 'ja');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Typography', 'TYPOGRAPHY', 'ja');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('さ入れ言葉', 'CAT8', 'ja');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('ら入れ言葉', 'CAT9', 'ja');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('ら抜き言葉', 'CAT6', 'ja');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('レタス言葉', 'CAT7', 'ja');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('文法', 'CAT1', 'ja');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('誤変換', 'CAT3', 'ja');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('誤字', 'CAT2', 'ja');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('連語関係', 'CAT4', 'ja');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('重複', 'CAT5', 'ja');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Compound_problems', 'COMPOUNDING', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Eventuellt ett stavfel', 'TYPOS', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammatik', 'GRAMMAR', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Kontamination', 'CAT7', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Ord som hor ihop', 'CAT5', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Ord som ofta förväxlas', 'CAT4', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Punctuation', 'PUNCTUATION', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Sammanskrivning rekomenderas', 'CAT2', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Stor eller liten bokstav', 'CASING', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Syntax', 'CAT6', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Särskrivning rekomenderas', 'CAT1', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Typography', 'TYPOGRAPHY', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('punkter efter förkortningar', 'CAT3', 'sv');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Övrigt', 'MISC', 'sv');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Acordul încrucișat', 'CAT11', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Cacofonie', 'CAT10', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Capitalizare', 'CASING', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Diverse', 'MISC', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Ghilimele', 'CAT2', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Greșeli de exprimare', 'CAT3', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Greșeli gramaticale - acord adjectiv', 'CAT5', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Greșeli gramaticale - acord predicat', 'CAT6', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Greșeli gramaticale - acord pronume', 'CAT8', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Greșeli gramaticale - acord substantiv', 'CAT4', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Greșeli gramaticale - acordul după caz', 'CAT7', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Litere inversate', 'CAT1', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Numeral', 'CAT13', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Pleonasme', 'CAT9', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Posibilă greșeală de tastare', 'TYPOS', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Punctuation', 'PUNCTUATION', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Punctuație', 'PUNCTUATION', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Repetiții', 'CAT12', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Style', 'STYLE', 'ro');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Typography', 'TYPOGRAPHY', 'ro');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Błędy fonetyczne', 'PHONETICS', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Błędy frazeologiczne', 'CONFUSED_WORDS', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Błędy interpunkcyjne', 'PUNCTUATION', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Błędy leksykalne', 'STYLE', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Błędy odmiany', 'GRAMMAR', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Błędy ortograficzne', 'SPELLING', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Błędy rodzaju gramatycznego', 'GENDER', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Błędy różne', 'MISC', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Błędy składniowe', 'SYNTAX', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Błędy typograficzne', 'TYPOGRAPHY', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Błędy w szyku wyrazów', 'WORD_ORDER', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Formatowanie liczb', 'NUMBERS', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Miscellaneous', 'MISC', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Pisownia małą i wielką literą', 'CASING', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Pleonazmy', 'REDUNDANCY', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Prawdopodobna literówka', 'TYPOS', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Prawdopodobne literówki', 'TYPOS', 'pl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Wyrazy modne i nadużywane', 'SEMANTICS', 'pl');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Велико/мало почетно слово', 'CASING', 'sr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Интерпункција', 'PUNCTUATION', 'sr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Логичке грешке', 'SR_LOGIC', 'sr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Могућа грешка', 'TYPOS', 'sr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Могуће грешке приликом писања', 'SR_TYPOS', 'sr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Разно', 'MISC', 'sr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Стил писања', 'SR_CAT_STYLE', 'sr');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Типографија', 'TYPOGRAPHY', 'sr');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Diverse', 'MISC', 'da');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Forkortelser med eller uden punktum', 'CAT4', 'da');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammatik', 'GRAMMAR', 'da');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Grammatik, komma', 'GRAMMAR_COMMA', 'da');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Mulig slåfejl', 'TYPOS', 'da');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Mulige ordforveksling', 'CAT2', 'da');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Mulige ordforveksling med sjældent ord', 'CAT3', 'da');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Mulige slåfejl', 'CAT1', 'da');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('STORE/små bogstaver', 'CASING', 'da');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Tegnsætning', 'PUNCTUATION', 'da');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Typografi', 'TYPOGRAPHY', 'da');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Možna tipkarska napaka', 'TYPOS', 'sl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Napake pri kraticah', 'CAT2', 'sl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Napake pri postavljanju ločil', 'CAT3', 'sl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Napake uporabe predlogov', 'CAT4', 'sl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Pogoste napake', 'CAT6', 'sl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Polvikanje', 'CAT5', 'sl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Postavitev ločil', 'PUNCTUATION', 'sl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Razno', 'MISC', 'sl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Slog - številke', 'CAT1', 'sl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Tipografija', 'TYPOGRAPHY', 'sl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Velike začetnice', 'CASING', 'sl');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('அச்சுக்கலை', 'TYPOGRAPHY', 'ta');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('இலக்கண அமைப்பில் சொற்கள்', 'CAT1', 'ta');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('சந்தி', 'CAT3', 'ta');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('தனிச் சொற்களை எழுதும் முறை', 'CAT2', 'ta');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('நிறுத்தக்குறியீடு', 'PUNCTUATION', 'ta');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('பாணி', 'STYLE', 'ta');

INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Adjective Plurality', 'ADJ_PLURAL', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Affix Usage', 'AFFIX_USAGE', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Alternation of D and R', 'D_AND_R', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Code-switching', 'CODE_SWITCHING', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Exchange Word Positions', 'WORD_POSITIONS', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('False Friend', 'FALSE_FRIENDS', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Kapitalisasiyon', 'CASING', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Ligature Usage', 'LIGATURE_USAGE', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Loan Words', 'LOAN_WORDS', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Missing Determiner', 'MISSING_DETERMINERS', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Missing Last Word', 'MISSING_LAST_WORD', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Missing Lexical Marker', 'MISSING_LEXICAL_MARKERS', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Ng and Nang', 'NG_NANG', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Posibleng Typo', 'TYPOS', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Punctuation', 'PUNCTUATION', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Typography', 'TYPOGRAPHY', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Word Repetition', 'REPETITION', 'tl');
INSERT INTO wp_proofreading_rules(`name`, `key`, `lang_code`) VALUES ('Wrong Determiner', 'DETERMINERS', 'tl');